export interface FlashCard {
    id: string;
    keyword: string;
    concept: string;
}

export const flashCardsData: Record<string, FlashCard[]> = {
    diversity: [
        { id: "d1", keyword: "Element", concept: "A substance that cannot be broken down into simpler substances by chemical methods." },
        { id: "d2", keyword: "Compound", concept: "A substance made of two or more elements chemically combined in a fixed ratio." },
        { id: "d3", keyword: "Mixture", concept: "Two or more substances not chemically combined and can be separated by physical means." },
        { id: "d4", keyword: "Solution", concept: "A homogeneous mixture of a solute dissolved in a solvent." },
        { id: "d5", keyword: "Suspension", concept: "A mixture containing insoluble fine solid particles in a liquid/gas." },
        { id: "d6", keyword: "Solubility", concept: "The maximum mass of solute that can dissolve in 100g of solvent at a specific temperature." },
        { id: "d7", keyword: "Filtration", concept: "Process of separating an insoluble solid from a liquid using a filter." },
        { id: "d8", keyword: "Evaporation", concept: "Separating a dissolved solid from a liquid by heating to dryness." },
        { id: "d9", keyword: "Distillation", concept: "Separating a pure liquid from a solution using boiling and condensation." },
        { id: "d10", keyword: "Chromatography", concept: "Separating components of a mixture based on their different solubilities in a solvent." },
        { id: "d11", keyword: "Solute", concept: "The substance that is dissolved in a solvent." },
        { id: "d12", keyword: "Solvent", concept: "The substance in which the solute dissolves." },
        { id: "d13", keyword: "Residue", concept: "The solid left on the filter paper after filtration." },
        { id: "d14", keyword: "Filtrate", concept: "The liquid that passes through the filter paper during filtration." },
        { id: "d15", keyword: "Distillate", concept: "The pure liquid collected after condensation in distillation." },
        { id: "d16", keyword: "Boiling Point", concept: "The temperature at which a liquid changes into a gas throughout the liquid." },
        { id: "d17", keyword: "Melting Point", concept: "The temperature at which a solid changes into a liquid." },
        { id: "d18", keyword: "Pure Substance", concept: "A substance with a fixed melting and boiling point." },
        { id: "d19", keyword: "Atomic Number", concept: "The number of protons in the nucleus of an atom." },
        { id: "d20", keyword: "Periodic Table", concept: "A table of elements arranged in order of increasing atomic number." },
    ],
    light: [
        { id: "l1", keyword: "Reflection", concept: "The bouncing of light off a surface." },
        { id: "l2", keyword: "Refraction", concept: "The bending of light as it passes from one transparent medium to another." },
        { id: "l3", keyword: "Incident Ray", concept: "The light ray that hits a surface." },
        { id: "l4", keyword: "Reflected Ray", concept: "The light ray that bounces off a surface." },
        { id: "l5", keyword: "Normal", concept: "An imaginary line perpendicular to the surface at the point of incidence." },
        { id: "l6", keyword: "Angle of Incidence", concept: "The angle between the incident ray and the normal." },
        { id: "l7", keyword: "Angle of Reflection", concept: "The angle between the reflected ray and the normal." },
        { id: "l8", keyword: "Plane Mirror", concept: "A flat mirror that forms an upright, virtual, and laterally inverted image." },
        { id: "l9", keyword: "Virtual Image", concept: "An image that cannot be formed on a screen." },
        { id: "l10", keyword: "Real Image", concept: "An image that can be formed on a screen." },
        { id: "l11", keyword: "Density", concept: "Optical density affects the speed and bending of light." },
        { id: "l12", keyword: "Convex Mirror", concept: "A mirror that curves outwards, giving a wider field of vision." },
        { id: "l13", keyword: "Concave Mirror", concept: "A mirror that curves inwards, used for magnifying or focusing light." },
        { id: "l14", keyword: "Dispersal", concept: "Splitting of white light into its component colors (spectrum)." },
        { id: "l15", keyword: "Spectrum", concept: "The range of colors of white light: Red, Orange, Yellow, Green, Blue, Indigo, Violet." },
        { id: "l16", keyword: "Concave Lens", concept: "A lens that diverges light rays." },
        { id: "l17", keyword: "Convex Lens", concept: "A lens that converges light rays to a focal point." },
        { id: "l18", keyword: "Focal Point", concept: "The point where parallel rays of light meet after passing through a convex lens." },
        { id: "l19", keyword: "Absorption", concept: "When light is taken in by a material and converted to energy (heat)." },
        { id: "l20", keyword: "Transmission", concept: "When light passes through a material (e.g., glass)." },
    ],
    cells: [
        { id: "c1", keyword: "Cell", concept: "The basic building block of life." },
        { id: "c2", keyword: "Nucleus", concept: "The part of the cell that contains genetic material and controls activities." },
        { id: "c3", keyword: "Cytoplasm", concept: "The jelly-like substance where most chemical reactions take place." },
        { id: "c4", keyword: "Cell Membrane", concept: "A thin outer layer that controls the movement of substances in and out of the cell." },
        { id: "c5", keyword: "Cell Wall", concept: "A rigid outer layer in plant cells that provides shape and support." },
        { id: "c6", keyword: "Chloroplast", concept: "Part of a plant cell where photosynthesis occurs." },
        { id: "c7", keyword: "Vacuole", concept: "A space in the cell containing cell sap or food (larger in plant cells)." },
        { id: "c8", keyword: "Mitochondria", concept: "The powerhouse of the cell where aerobic respiration occurs." },
        { id: "c9", keyword: "Ribosome", concept: "The site of protein synthesis in a cell." },
        { id: "c10", keyword: "Tissue", concept: "A group of similar cells working together to perform a function." },
        { id: "c11", keyword: "Organ", concept: "A group of different tissues working together (e.g., heart, leaf)." },
        { id: "c12", keyword: "System", concept: "A group of organs working together (e.g., digestive system)." },
        { id: "c13", keyword: "Multicellular", concept: "Organisms made up of many cells." },
        { id: "c14", keyword: "Unicellular", concept: "Organisms made up of only one cell." },
        { id: "c15", keyword: "Specialised Cell", concept: "A cell that has a specific structure to perform a particular function." },
        { id: "c16", keyword: "Root Hair Cell", concept: "Specialised plant cell with long projection for absorbing water and minerals." },
        { id: "c17", keyword: "Red Blood Cell", concept: "Specialised animal cell containing haemoglobin to transport oxygen." },
        { id: "c18", keyword: "Muscle Cell", concept: "Specialised cell that can contract and relax to produce movement." },
        { id: "c19", keyword: "Diffusion", concept: "Net movement of particles from a region of higher to lower concentration." },
        { id: "c20", keyword: "Osmosis", concept: "Net movement of water molecules from a region of higher to lower water potential through a partially permeable membrane." },
    ],
    matter: [
        { id: "m1", keyword: "Atom", concept: "The smallest unit of an element." },
        { id: "m2", keyword: "Molecule", concept: "Two or more atoms chemically combined." },
        { id: "m3", keyword: "Proton", concept: "A positively charged subatomic particle in the nucleus." },
        { id: "m4", keyword: "Neutron", concept: "A neutral subatomic particle in the nucleus." },
        { id: "m5", keyword: "Electron", concept: "A negatively charged subatomic particle orbiting the nucleus in shells." },
        { id: "m6", keyword: "Nucleus (Atom)", concept: "The dense center containing protons and neutrons." },
        { id: "m7", keyword: "Valence Electron", concept: "Electrons in the outermost shell of an atom." },
        { id: "m8", keyword: "Ion", concept: "An atom that has gained or lost electrons, becoming charged." },
        { id: "m9", keyword: "Cation", concept: "A positively charged ion (loss of electrons)." },
        { id: "m10", keyword: "Anion", concept: "A negatively charged ion (gain of electrons)." },
        { id: "m11", keyword: "Isotope", concept: "Atoms of the same element with different numbers of neutrons." },
        { id: "m12", keyword: "Kinetic Particle Theory", concept: "Matter is made of tiny particles in constant random motion." },
        { id: "m13", keyword: "Solid", concept: "State of matter with fixed shape and volume; particles vibrate in fixed positions." },
        { id: "m14", keyword: "Liquid", concept: "State of matter with fixed volume but no fixed shape; particles slide over each other." },
        { id: "m15", keyword: "Gas", concept: "State of matter with no fixed shape or volume; particles move rapidly and randomly." },
        { id: "m16", keyword: "Sublimation", concept: "The change from solid directly to gas without becoming liquid." },
        { id: "m17", keyword: "Condensation", concept: "The change from gas to liquid." },
        { id: "m18", keyword: "Freezing", concept: "The change from liquid to solid." },
        { id: "m19", keyword: "Expansion", concept: "Increase in volume when particles gain heat and move further apart." },
        { id: "m20", keyword: "Contraction", concept: "Decrease in volume when particles lose heat and move closer together." },
    ],
    forces: [
        { id: "f1", keyword: "Force", concept: "A push or a pull." },
        { id: "f2", keyword: "Newton (N)", concept: "The SI unit of force." },
        { id: "f3", keyword: "Friction", concept: "A contact force that opposes motion." },
        { id: "f4", keyword: "Gravitational Force", concept: "A non-contact force that pulls objects towards the center of the Earth." },
        { id: "f5", keyword: "Magnetic Force", concept: "A non-contact force of attraction or repulsion between magnets or magnetic materials." },
        { id: "f6", keyword: "Elastic Spring Force", concept: "Force exerted by a compressed or stretched spring to return to its original length." },
        { id: "f7", keyword: "Weight", concept: "The gravitational force acting on an object (W = mg)." },
        { id: "f8", keyword: "Mass", concept: "The amount of matter in an object; constant everywhere." },
        { id: "f9", keyword: "Pressure", concept: "Force acting per unit area (P = F/A)." },
        { id: "f10", keyword: "Pascal (Pa)", concept: "The SI unit of pressure." },
        { id: "f11", keyword: "Atmospheric Pressure", concept: "The pressure exerted by the weight of air in the atmosphere." },
        { id: "f12", keyword: "Balanced Forces", concept: "Forces acting on an object that are equal in size and opposite in direction (Resultant = 0)." },
        { id: "f13", keyword: "Unbalanced Forces", concept: "Forces that cause a change in the state of motion of an object." },
        { id: "f14", keyword: "Inertia", concept: "Reluctance of an object to change its state of rest or motion." },
        { id: "f15", keyword: "Density", concept: "Mass per unit volume (D = m/V)." },
        { id: "f16", keyword: "Air Resistance", concept: "Frictional force exerted by air on moving objects." },
        { id: "f17", keyword: "Lubricant", concept: "Substance used to reduce friction between surfaces." },
        { id: "f18", keyword: "Contact Force", concept: "Force that requires physical contact (e.g., friction)." },
        { id: "f19", keyword: "Non-contact Force", concept: "Force that acts over a distance (e.g., gravity, magnetism)." },
        { id: "f20", keyword: "Resultant Force", concept: "The single force that represents the combined effect of all forces acting on an object." },
    ],
    energy: [
        { id: "e1", keyword: "Energy", concept: "The capacity to do work." },
        { id: "e2", keyword: "Joule (J)", concept: "The SI unit of energy and work." },
        { id: "e3", keyword: "Kinetic Energy", concept: "Energy possessed by moving objects." },
        { id: "e4", keyword: "Gravitational Potential Energy", concept: "Energy stored in an object due to its height from the ground." },
        { id: "e5", keyword: "Elastic Potential Energy", concept: "Energy stored in a stretched or compressed object." },
        { id: "e6", keyword: "Chemical Potential Energy", concept: "Energy stored in food, fuels, and batteries." },
        { id: "e7", keyword: "Principle of Conservation of Energy", concept: "Energy cannot be created or destroyed, only converted from one form to another." },
        { id: "e8", keyword: "Conduction", concept: "Heat transfer through a medium without the movement of the medium itself." },
        { id: "e9", keyword: "Convection", concept: "Heat transfer in fluids (liquids/gases) by the movement of the fluid itself." },
        { id: "e10", keyword: "Radiation", concept: "Heat transfer in the form of electromagnetic waves; requires no medium." },
        { id: "e11", keyword: "Work Done", concept: "W = Force x distance moved in direction of force." },
        { id: "e12", keyword: "Thermal Energy", concept: "Energy associated with the temperature of an object." },
        { id: "e13", keyword: "Insulator", concept: "A material that is a poor conductor of heat or electricity." },
        { id: "e14", keyword: "Conductor", concept: "A material that allows heat or electricity to pass through easily." },
        { id: "e15", keyword: "Renewable Energy", concept: "Energy from sources that can be replenished (e.g., solar, wind)." },
        { id: "e16", keyword: "Non-renewable Energy", concept: "Energy from sources that will run out (e.g., coal, oil)." },
        { id: "e17", keyword: "Efficiency", concept: "(Useful output energy / Input energy) x 100%." },
        { id: "e18", keyword: "Temperature", concept: "A measure of the average kinetic energy of particles." },
        { id: "e19", keyword: "Specific Heat Capacity", concept: "Energy needed to raise the temperature of 1kg of a substance by 1°C." },
        { id: "e20", keyword: "Bimetallic Strip", concept: "Two metals with different expansion rates, used in thermostats." },
    ],
    ecosystems: [
        { id: "ec1", keyword: "Ecosystem", concept: "A group of living organisms interacting with each other and their environment." },
        { id: "ec2", keyword: "Population", concept: "A group of organisms of the same species living in a habitat." },
        { id: "ec3", keyword: "Community", concept: "Different populations living and interacting in a habitat." },
        { id: "ec4", keyword: "Habitat", concept: "The place where an organism lives." },
        { id: "ec5", keyword: "Abiotic Factors", concept: "Non-living components (e.g., light, temperature, pH)." },
        { id: "ec6", keyword: "Biotic Factors", concept: "Living components (e.g., predators, prey, decomposers)." },
        { id: "ec7", keyword: "Producer", concept: "Organisms (plants) that make their own food through photosynthesis." },
        { id: "ec8", keyword: "Consumer", concept: "Organisms that obtain energy by feeding on others." },
        { id: "ec9", keyword: "Decomposer", concept: "Organisms (fungi, bacteria) that break down dead matter." },
        { id: "ec10", keyword: "Food Chain", concept: "A linear sequence showing the flow of energy from one organism to another." },
        { id: "ec11", keyword: "Food Web", concept: "A series of interconnected food chains." },
        { id: "ec12", keyword: "Trophic Level", concept: "The position an organism occupies in a food chain." },
        { id: "ec13", keyword: "Energy Flow", concept: "Energy is lost as heat or through metabolism at each level (10% rule)." },
        { id: "ec14", keyword: "Parasitism", concept: "Interaction where one benefits and the other is harmed (e.g., tick on dog)." },
        { id: "ec15", keyword: "Mutualism", concept: "Interaction where both organisms benefit (e.g., bee and flower)." },
        { id: "ec16", keyword: "Commensalism", concept: "Interaction where one benefits and the other is neither helped nor harmed." },
        { id: "ec17", keyword: "Adaptation", concept: "A characteristic that helps an organism survive in its environment." },
        { id: "ec18", keyword: "Carbon Cycle", concept: "Process by which carbon moves through the environment and living things." },
        { id: "ec19", keyword: "Deforestation", concept: "Clearing of forests, leading to loss of habitat and climate change." },
        { id: "ec20", keyword: "Global Warming", concept: "Increase in Earth's temperature due to greenhouse gases like CO2." },
    ],
    digestion: [
        { id: "di1", keyword: "Digestion", concept: "Breaking down of large, complex food molecules into small, soluble ones." },
        { id: "di2", keyword: "Physical Digestion", concept: "Mechanical breakdown (e.g., chewing, churning) without changing chemical composition." },
        { id: "di3", keyword: "Chemical Digestion", concept: "Breakdown of food using enzymes." },
        { id: "di4", keyword: "Enzyme", concept: "A biological catalyst that speeds up chemical reactions." },
        { id: "di5", keyword: "Alimentary Canal", concept: "The pathway food takes (mouth to anus)." },
        { id: "di6", keyword: "Mouth", concept: "Where starch digestion begins via salivary amylase." },
        { id: "di7", keyword: "Esophagus", concept: "Tube connecting mouth to stomach; uses peristalsis." },
        { id: "di8", keyword: "Stomach", concept: "Where protein digestion begins; contains hydrochloric acid." },
        { id: "di9", keyword: "Small Intestine", concept: "Where most chemical digestion and absorption occurs." },
        { id: "di10", keyword: "Large Intestine", concept: "Where water and mineral salts are absorbed." },
        { id: "di11", keyword: "Liver", concept: "Produces bile to emulsify fats." },
        { id: "di12", keyword: "Gall Bladder", concept: "Stores bile produced by the liver." },
        { id: "di13", keyword: "Pancreas", concept: "Produces pancreatic juice containing multiple enzymes." },
        { id: "di14", keyword: "Amylase", concept: "Enzyme that breaks down starch into maltose." },
        { id: "di15", keyword: "Protease", concept: "Enzyme that breaks down proteins into polypeptides/amino acids." },
        { id: "di16", keyword: "Lipase", concept: "Enzyme that breaks down fats into fatty acids and glycerol." },
        { id: "di17", keyword: "Villi", concept: "Finger-like projections in the small intestine that increase surface area for absorption." },
        { id: "di18", keyword: "Peristalsis", concept: "Wave-like muscle contractions that push food along the gut." },
        { id: "di19", keyword: "Absorption", concept: "Taking in small soluble food molecules into the bloodstream." },
        { id: "di20", keyword: "Assimilation", concept: "Using absorbed food to build new protoplasm or produce energy." },
    ],
    transport: [
        { id: "t1", keyword: "Circulatory System", concept: "Transport system in humans (heart, blood, blood vessels)." },
        { id: "t2", keyword: "Heart", concept: "Muscular organ that pumps blood throughout the body." },
        { id: "t3", keyword: "Artery", concept: "Blood vessel that carries oxygenated blood away from the heart (except pulmonary artery)." },
        { id: "t4", keyword: "Vein", concept: "Blood vessel that carries deoxygenated blood towards the heart; has valves." },
        { id: "t5", keyword: "Capillary", concept: "Tiny, one-cell thick blood vessel where exchange of materials occurs." },
        { id: "t6", keyword: "Plasma", concept: "Liquid part of the blood that transports hormones, nutrients, and waste." },
        { id: "t7", keyword: "Red Blood Cells", concept: "Cells containing haemoglobin to transport oxygen." },
        { id: "t8", keyword: "White Blood Cells", concept: "Cells involved in the immune response (fighting infections)." },
        { id: "t9", keyword: "Platelets", concept: "Fragments of cells involved in blood clotting." },
        { id: "t10", keyword: "Double Circulation", concept: "Blood passes through the heart twice in one complete circuit (pulmonary and systemic)." },
        { id: "t11", keyword: "Xylem", concept: "Plant tissue that transports water and mineral salts upwards." },
        { id: "t12", keyword: "Phloem", concept: "Plant tissue that transports manufactured food (sugar) from leaves to other parts." },
        { id: "t13", keyword: "Transpiration", concept: "Loss of water vapor from the leaves of a plant through stomata." },
        { id: "t14", keyword: "Stomata", concept: "Small pores on leaf surfaces regulated by guard cells." },
        { id: "t15", keyword: "Haemoglobin", concept: "Iron-containing protein in red blood cells that binds to oxygen." },
        { id: "t16", keyword: "Vascular Bundle", concept: "Group containing xylem and phloem in plants." },
        { id: "t17", keyword: "Diffusion (Transport)", concept: "Exchange of gases in capillaries." },
        { id: "t18", keyword: "Root Hairs", concept: "Increase surface area for absorption of water and minerals." },
        { id: "t19", keyword: "Pulmonary Circulation", concept: "Circulation of blood between the heart and the lungs." },
        { id: "t20", keyword: "Systemic Circulation", concept: "Circulation of blood between the heart and the rest of the body." },
    ],
    reproduction: [
        { id: "r1", keyword: "Puberty", concept: "Stage of development where an individual becomes capable of reproduction." },
        { id: "r2", keyword: "Testis", concept: "Organ in males that produces sperm and testosterone." },
        { id: "r3", keyword: "Sperm", concept: "The male gamete (sex cell)." },
        { id: "r4", keyword: "Ovary", concept: "Organ in females that produces eggs (ova) and hormones." },
        { id: "r5", keyword: "Ovum", concept: "The female gamete (egg cell)." },
        { id: "r6", keyword: "Oviduct (Fallopian Tube)", concept: "Where fertilization typically occurs." },
        { id: "r7", keyword: "Uterus (Womb)", concept: "Where the embryo implants and develops." },
        { id: "r8", keyword: "Menstrual Cycle", concept: "Monthly cycle of changes in the female reproductive system (~28 days)." },
        { id: "r9", keyword: "Menstruation", concept: "The shedding of the uterine lining (Day 1-5)." },
        { id: "r10", keyword: "Ovulation", concept: "The release of a mature egg from the ovary (around Day 14)." },
        { id: "r11", keyword: "Fertilization", concept: "The fusion of a sperm nucleus with an egg nucleus to form a zygote." },
        { id: "r12", keyword: "Zygote", concept: "A fertilized egg." },
        { id: "r13", keyword: "Embryo", concept: "The early stage of development after the zygote divides." },
        { id: "r14", keyword: "Contraception", concept: "Methods used to prevent pregnancy (e.g., condom, pill)." },
        { id: "r15", keyword: "Hormones", concept: "Chemical messengers (e.g., Estrogen, Testosterone)." },
        { id: "r16", keyword: "Sexually Transmitted Infections (STIs)", concept: "Infections spread through sexual contact (e.g., HIV, Syphilis)." },
        { id: "r17", keyword: "HIV/AIDS", concept: "Virus that attacks the immune system." },
        { id: "r18", keyword: "Implantation", concept: "When the embryo attaches to the thick uterine lining." },
        { id: "r19", keyword: "Placenta", concept: "Organ that allows exchange of nutrients/waste between mother and fetus." },
        { id: "r20", keyword: "Asexual Reproduction", concept: "Reproduction involving only one parent, producing identical offspring." },
    ],
    electrical: [
        { id: "el1", keyword: "Electric Current", concept: "Rate of flow of electric charges." },
        { id: "el2", keyword: "Ampere (A)", concept: "The SI unit of electric current." },
        { id: "el3", keyword: "Ammeter", concept: "Instrument used to measure electric current; connected in series." },
        { id: "el4", keyword: "Potential Difference (Voltage)", concept: "Energy converted per unit charge passing between two points." },
        { id: "el5", keyword: "Volt (V)", concept: "The SI unit of potential difference." },
        { id: "el6", keyword: "Voltmeter", concept: "Instrument used to measure voltage; connected in parallel." },
        { id: "el7", keyword: "Resistance", concept: "The opposition to the flow of electric current (R = V/I)." },
        { id: "el8", keyword: "Ohm (Ω)", concept: "The SI unit of electrical resistance." },
        { id: "el9", keyword: "Series Circuit", concept: "A circuit with only one path for current to flow." },
        { id: "el10", keyword: "Parallel Circuit", concept: "A circuit with multiple paths for current to flow." },
        { id: "el11", keyword: "Conductor (Electrical)", concept: "Material that allows electricity to flow easily (e.g., copper)." },
        { id: "el12", keyword: "Insulator (Electrical)", concept: "Material that does not allow electricity to flow easily (e.g., plastic)." },
        { id: "el13", keyword: "Variable Resistor (Rheostat)", concept: "A component used to change the resistance in a circuit." },
        { id: "el14", keyword: "Power (Electrical)", concept: "Rate at which electrical energy is converted (P = VI)." },
        { id: "el15", keyword: "Watt (W)", concept: "The SI unit of power." },
        { id: "el16", keyword: "Fuse", concept: "A safety device that melts and breaks the circuit if current is too high." },
        { id: "el17", keyword: "Circuit Breaker", concept: "A switch that automatically opens if current exceeds safety levels." },
        { id: "el18", keyword: "Earth Wire", concept: "Safety wire that provides a low-resistance path to ground." },
        { id: "el19", keyword: "Short Circuit", concept: "A path of very low resistance that bypasses components." },
        { id: "el20", keyword: "Kilowatt-hour (kWh)", concept: "Unit of electrical energy used for billing." },
    ],
};
